# Generated by Django 5.2.4 on 2026-06-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="last_name",
            new_name="surname",
        ),
    ]
